### ISSUE TITLE
Can't resolve sound issue

### ISSUE THREAD

**Issue by mrjackyliang** [robwolff3/google-assistant-webserver#4]
@robwolff3 I tried to install the container on my Synology, but I can't seem to make the sound card work. Any ideas on implementing a dummy sound card?

**Comment by robwolff3** [comment]
Personally I do not have any experience with Synology devices. Only thing I could suggest is manipulating the "device" option to what the equivalent might be for Synology. https://docs.docker.com/compose/compose-file/#devices

**Comment by ghust** [comment]
I'm going to add on this one.

I tried installing it just as you did in the howto and get the following error:

ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
[FATAL:audio_input_stream.cc(47)] Input device could not be opened: default

Do you have any idea what could be causing this? Do I need to install some dummy device on my host? Or what's the logic behind the "device" step?

Best regards

**Comment by mrjackyliang** [comment]
I just bought a cheap sound device from Amazon and hooked it into the USB port. Seems to work!
